name: DevSecOps CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  REGISTRY_NAME: acrpracticeprod01
  CLUSTER_NAME: akspracticeprod01
  CLUSTER_RESOURCE_GROUP: rsgpracticeprod
  NAMESPACE: hello-app
  APP_NAME: hello-app

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Generate version tag
      id: version
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        VERSION="1.0.${COMMIT_COUNT}"
        echo "version=${VERSION}" >> $GITHUB_OUTPUT
        echo "full-image-name=${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${VERSION}" >> $GITHUB_OUTPUT
        echo "Generated version: ${VERSION}"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ steps.version.outputs.version }}
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest
        platforms: linux/amd64

    - name: Wait for image to be available
      run: sleep 10

    - name: Scan container image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ steps.version.outputs.full-image-name }}
        format: 'table'
        exit-code: '0'
        
    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  # k8s-security:
  #   name: K8s Security Check
  #   runs-on: ubuntu-latest
  #   needs: build-test
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Run kubesec scan
  #     run: |
  #       # Install kubesec
  #       curl -sSL https://github.com/controlplaneio/kubesec/releases/latest/download/kubesec_linux_amd64.tar.gz | tar xz
  #       sudo mv kubesec /usr/local/bin/
        
  #       # Scan K8s manifests
  #       kubesec scan k8s/deployment.yaml
  #       kubesec scan k8s/service.yaml

  # deploy-to-aks:
  #   name: Deploy to AKS
  #   runs-on: ubuntu-latest
  #   needs: [build-test, k8s-security]
  #   if: github.ref == 'refs/heads/main'
  #   environment: production
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4

  #   - name: Azure Login
  #     uses: azure/login@v1
  #     with:
  #       creds: ${{ secrets.AZURE_CREDENTIALS }}

  #   - name: Set up kubectl
  #     uses: azure/aks-set-context@v3
  #     with:
  #       resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}
  #       cluster-name: ${{ env.CLUSTER_NAME }}

  #   - name: Update image tag in manifests
  #     run: |
  #       sed -i "s|acrpracticeprod01.azurecr.io/hello-app:latest|${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:sha-${{ github.sha }}|g" k8s/deployment.yaml

  #   - name: Deploy to AKS
  #     run: |
  #       kubectl apply -f k8s/
  #       kubectl rollout status deployment/hello-deployment -n ${{ env.NAMESPACE }} --timeout=300s
  #       kubectl get pods -n ${{ env.NAMESPACE }}

  #   - name: Verify deployment
  #     run: |
  #       # Wait a bit for service to be ready
  #       sleep 30
        
  #       # Check if pods are running
  #       kubectl get pods -n ${{ env.NAMESPACE }} -l app=hello-app --field-selector=status.phase=Running
        
  #       echo "Deployment completed successfully!"